# Generated by Django 4.0 on 2023-04-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table="'core.post'",
        ),
    ]
