# Generated by Django 4.0 on 2023-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_project', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
