# Generated by Django 4.0 on 2023-05-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_project', '0006_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
