# Generated by Django 4.0 on 2023-03-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
