# Generated by Django 4.0 on 2023-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Coordinator'), (1, 'Instructor'), (2, 'Student')], default=2, max_length=1, null=True, verbose_name='Role status'),
        ),
    ]
