# Generated by Django 4.0 on 2023-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0009_skill_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
